### ISSUE TITLE
Wrong refreshAccessToken call

### ISSUE THREAD

**Issue by LucidComplex** [realm/realm-graphql#11]
`authenticationHelper.js` has the wrong arguments passed.

`refreshAccessToken(user, realmPath)` is wrongly called with a single object containing the two arguments. I believe this can be fixed with the spread operator?

**Comment by nirinchev** [comment]
Can you share more information about where this wrong call originates from/how does it manifest itself? As far as I can see, it's used twice in non-test files and in both cases it's called with two arguments, not one:

https://github.com/realm/realm-graphql/blob/master/src/graphqlConfig.ts#L66
https://github.com/realm/realm-graphql/blob/master/src/graphqlConfig.ts#L168

**Comment by LucidComplex** [comment]
Sorry, I dug into the code and found the issue is with the documentation.

The `GraphQLConfig.create` static function expects `user` and `realmPath` separately, not as a single object as the README says.

**Comment by nirinchev** [comment]
Sorry about that. I updated the readme to reflect the code :)
