### ISSUE TITLE
Following LinkingObjects for query

### ISSUE THREAD

**Issue by LucidComplex** [realm/realm-graphql#12]
Hi, is there a way to query on a linking object? Like so:

schema:
```js
const AuthorSchema = {
    name: 'Author',
    properties: {
        name: 'string'
        books: 'Book[]'
    }
};

const BookSchema = {
    name: 'Book',
    properties: {
        title: 'string',
        author: {type: 'linkingObjects', objectType: 'Author', property: 'books'}
    }
};
```

query:
```graphql
query {
    book(query: "author.name BEGINSWITH 'Charles'") {
        title
    }
}
```

I currently get the error that "No property 'author' on object of type 'Book".

Is it possible?

**Comment by SogoGolf** [comment]
we really need this too. is this in development/planned ?

**Comment by nirinchev** [comment]
I believe this should be possible today. @ironage can you provide an example of the syntax?

**Comment by SogoGolf** [comment]
brilliant many thanks

**Comment by ironage** [comment]
Yes, it is supported from realm js version 2.3.4 and up. 
The syntax is the same as querying any other property: `author.name BEGINSWITH 'Charles'`
Or if you haven't made a linking objects property, you can go through the forward link if you use realm js >= 2.4.1 `@links.Author.books.name beginswith 'Charles'`

**Comment by SogoGolf** [comment]
thanks @ironage . you are right this does work via the Realm JS API, however it does not seem to work for realm-graphql-client queries. 

For example this does not work (throws gql error):
```
{
  golfers(query: "clubs.id = 'c6785efe-f62f-4b15-9fb7-ea2da164fa67'") {
    firstName
    lastName
  }
}
```
"clubs" is defined like this in the Realm schema (for Golfer):
```
clubs: {
      type: "linkingObjects",
      objectType: "Club",
      property: "golfers"
    },
```

(the equivalent Realm JS query does work):
```
var clubsForGolfer = realm.objects("golfer").filtered(
    `clubs.id = "c6785efe-f62f-4b15-9fb7-ea2da164fa67"`
  );
```

Can this Realm JS API functionality be exposed via **realm-graphql-client** ?

**Comment by nirinchev** [comment]
The server Realms don't have named linking objects properties defined, so you can't use the first example syntax. You need to use the second one where you fully describe the link.

**Comment by SogoGolf** [comment]
ok gotcha sorry i just tried that and it did indeed work via gql query. for example:

```
{
  golfers(query: "@links.Club.golfers.id = '3f9dbf5f-7f47-4cf3-9492-489cdf324f7c'") {
    firstName
    lastName
  }
}
```

**Comment by nirinchev** [comment]
Glad to hear that 🙌 I'll close this then and update the Readme.
