### ISSUE TITLE
Install fails because of local reference in package.json

### ISSUE THREAD

**Issue by olivereisenhut** [realm/realm-graphql#14]
Following the section: 'Developing the client' `npm install` was executed.  npm throw an error because a local file was not found:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../realm-object-server-graphql" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oeisenhut/.npm/_logs/2018-02-23T19_58_48_012Z-debug.log
```

You can't run the tests because the installation is not possible. Please consider add a package or provide a guide where to put this repository to.

**Comment by idkjs** [comment]
I got a similar error because I didnt have nvm node version manager installed as seems to be prefered by realm. Installing nvm fixed it but thats not something you should have to do as far as I can tell.

**Comment by nirinchev** [comment]
Sorry about that - it was a leftover from before the package was published, so I was developing both the client and the service locally. It should be fixed now.
