### ISSUE TITLE
Travis build not running

### ISSUE THREAD

**Issue by olivereisenhut** [realm/realm-graphql#21]
Despite of the existing `.travis.yml` there is is no build or tests running. See [here](https://travis-ci.org/realm/realm-graphql). 

Enabling Travis would show if PR's are breaking build or the logic.

**Comment by astigsen** [comment]
@nirinchev is this something we should enable?

**Comment by nirinchev** [comment]
Removed .travis.yml. We should setup a jenkins build for that repo but it's not a super high priority.
