### ISSUE TITLE
Unexpected installation warnings: Let's use apollo-boost instead of apollo-client-preset

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-graphql#24]
When I followed the instructions to install this from the `README.md` I got these warnings:

> npm WARN deprecated apollo-client-preset@1.0.8: for the best quick start with Apollo Client, please use apollo-boost instead
> npm WARN subscriptions-transport-ws@0.9.9 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.1 but none is installed. You must install peer dependencies yourself.
> npm WARN apollo-cache-inmemory@1.2.2 requires a peer of graphql@0.11.7 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
> npm WARN graphql-tag@2.9.2 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
> npm WARN apollo-client@2.3.2 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
> npm WARN apollo-link@1.2.2 requires a peer of graphql@^0.11.3 || ^0.12.3 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
> npm WARN apollo-link-http@1.5.4 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
> npm WARN apollo-link-http-common@0.2.4 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

The first suggests to use `apollo-boost` instead of `apollo-client-preset`, perhaps the guide could be simplified by doing that? And the rest is complaints that `graphql` is a peerDependency that is not installed - perhaps `graphql` should be added to the list of prerequisite packages?

**Comment by astigsen** [comment]
@nirinchev @kraenhansen is this still relevant?

**Comment by nirinchev** [comment]
Yes
