### ISSUE TITLE
Field Query can only be defined once

### ISSUE THREAD

**Issue by sipersso** [realm/realm-graphql#27]
Trying to get the GraphQL client working but failing. I am able to get an authenticated client, but all queries fail. 

Are there any naming restrictions in the realm schema? I am guessing that the name 'SetData' could cause problems?

`Internal server error: Error: Field Query.setData can only be defined once. Field Mutation.deleteSetData can only be defined once. at assertValidSchema (/app/node_modules/graphql/type/validate.js:82:11) at Object.validate (/app/node_modules/graphql/validation/validate.js:58:35) at doRunQuery (/app/node_modules/apollo-server-core/dist/runQuery.js:110:38) at /app/node_modules/apollo-server-core/dist/runQuery.js:21:56 at <anonymous>`

**Comment by nirinchev** [comment]
Which version of the service are you using? Versions prior to 3.0.0 had a limitation that class names must be singular (setData is plural). In 3.0.0 we lifted this limitation, although the resulting nodes will be grammatically incorrect - e.g. `data` becomes `datas` and so on.

**Comment by sipersso** [comment]
I am using Realm Cloud. Realm Studio says the version is 3.9.0?

**Comment by nirinchev** [comment]
Right... We'll roll out an update of the GraphQL service over the next few days. If that's blocking you, can you give me your instance url and I'll manually upgrade your instance.

**Comment by sipersso** [comment]
I can wait a few days, no problems. I can focus on other tasks until then. Can you notify me when it is out?

**Comment by astigsen** [comment]
Closing this for now as the GraphQL service should be updated by now. Please reopen if the problem reappears.
