### ISSUE TITLE
Unable to make graphql query

### ISSUE THREAD

**Issue by ziplizard** [realm/realm-graphql#31]
I've setup a `realm-graphql-client` almost identical to [here](https://realm.io/docs/realm-object-server/latest/api/graphql/). It authenticates as it should, the makes the query to my cloud instance. However, I get this response: `(node:54968) UnhandledPromiseRejectionWarning: Error: Network error: Response not successful: Received status code 400`. Is there something I have to setup on the cloud side for graphql to work?

**Comment by nirinchev** [comment]
No - GraphQL is enabled on cloud automatically. The body of the response should contain information about what went wrong, but because it's thrown as an unhandled promise rejection, it may not be trivial to get to it. Perhaps, if you post a minimal repro, I can try and see what's wrong.

**Comment by ziplizard** [comment]
```
const { ApolloClient, concat, HttpLink, InMemoryCache, gql } = require('apollo-boost');
const fetch = require('node-fetch');

const { Credentials, User, GraphQLConfig } = require('realm-graphql-client');
const SERVER_URL = 'my-realm-instance.us1a.cloud.realm.io';

const main = async () => {
  const credentials = Credentials.usernamePassword('my-username', 'my-password');
  const adminUser = await User.authenticate(credentials, `https://${SERVER_URL}`);
  const config = await GraphQLConfig.create(adminUser, '/ToDo');

  const httpLink = concat(
    config.authLink,
    new HttpLink({ uri: config.httpEndpoint, fetch }),
  );

  const client = new ApolloClient({
    link: httpLink,
    cache: new InMemoryCache()
  });

  const response = await client.query({
    query: gql`
      query {
        items {
          itemId
          body
          idDone
          timestamp
        }
      }
    `,
  });

  console.log('response: ', response);
};

try {
  main()
} catch(error) {
  console.log('error: ', error);
}
```

**Comment by ziplizard** [comment]
I found what I did wrong. I typod the field `isDone` above. The error response was not intuitive. Thanks tho.

**Comment by nirinchev** [comment]
`main` is asynchronous, so you need to await it for the catch to work. I expect that the error would have contained the information about which field is wrong. In any case, closing as it is working now.
