### ISSUE TITLE
How to explore graphql

### ISSUE THREAD

**Issue by ziplizard** [realm/realm-graphql#32]
I am unable to browse to `<my-realm-cloud-instance>/graphql/explore/<my-path>`. I get this response:
```
{
"type": "https://realm.io/docs/object-server/problems/access-denied",
"title": "The path is invalid or current user has no access.",
"status": 403,
"detail": "Authorization header is missing.",
"code": 614
}
```
When I try POST in postman to `<my-realm-cloud-instance>/auth`, I successfully get a token. I then use that token in postman to GET `<my-realm-cloud-instance>/graphql/explore/<my-path>`, and get this response:
```
{
    "type": "https://realm.io/docs/object-server/problems/invalid-credentials",
    "title": "The provided credentials are invalid or the user does not exist.",
    "status": 401,
    "detail": "The token data could not be verified against its signature",
    "code": 611
}
```
What am I doing wrong? I feel I should be able to explore my graphql schema without difficulty.

**Comment by ziplizard** [comment]
Related [here](https://github.com/realm/realm-graphql/issues/31)

**Comment by nirinchev** [comment]
`The token data could not be verified against its signature` means you probably didn't copy the entire authentication token string. The explorer is a web app that requires authentication. To be able to use it, you need to obtain an access token following the instructions here: https://github.com/realm/realm-graphql-service#obtaining-an-access-token. After you have one, you can use a chrome extension, such as [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj) to inject an `Authorization` header into your browser requests.

**Comment by ziplizard** [comment]
This [obtaining-an-access-token](https://github.com/realm/realm-graphql-service#obtaining-an-access-token), is precisely what I'm doing, as mentioned above with `/auth` to get the error.

**Comment by ziplizard** [comment]
Thanks for the guidance. I was missing doing the 2nd `/auth` call. And good advice on using ModHeader. These instructions really should be documented.

**Comment by nirinchev** [comment]
@mgeerling something to add to the docs todo.

**Comment by ziplizard** [comment]
For some reason I am no longer able to explore GraphQL. To my knowledge nothing has changed. I get a new refresh/access token and use it in the ModHeader, and get the error: `The provided credentials are invalid or the user does not exist.`
What am I doing wrong?

**Comment by ziplizard** [comment]
Figured it out. You guys don't want `Bearer` on it. However, now I'm getting this response in the GraphiQL interface: `Invalid options provided to ApolloServer: Syntax Error: Expected Name, found }`

**Comment by nirinchev** [comment]
This means that the schema of the Realm you're trying to browse is empty.

**Comment by ziplizard** [comment]
So what's wrong with the schema I have?  Because I most certainly have schema in there with hundreds of records.

**Comment by ziplizard** [comment]
Realm: /VSTest
Web Url: https://vstest.us1a.cloud.realm.io/graphql/explore/%2fVSTest

**Comment by nirinchev** [comment]
I've identified and fixed the cause of this problem. It happens because you have a class that has no properties. I've released a fix that will get deployed on your instance during the next maintenance window. If you don't want to wait, I can go ahead and deploy it manually, but that'll cause a 30-60 second downtime. Let me know if you want me to proceed with the manual update.
