### ISSUE TITLE
Creating a partial realm with logged in user in graphql doesnt initialize the realm correctly

### ISSUE THREAD

**Issue by henghonglee** [realm/realm-graphql#33]
Seems like the realms that we create with GraphQLConfig are not properly setup after creating the new SyncUser. Specifically im not seeing the system classes setup correctly (these get setup properly when i use a mobile sdk)

More Information: When trying to create an object using a graphql mutation after creating the syncUser and a new partial realm(thats not correctly setup), i get a success result, but i dont see the new object in the realm on realm studio

code and screenshots attached below

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { GraphQLConfig } from 'realm-graphql-client';
import { concat, HttpLink } from 'apollo-client-preset';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { WebSocketLink } from 'apollo-link-ws';
import { split } from 'apollo-client-preset';
import { getMainDefinition } from 'apollo-utilities';
import { Credentials, User } from 'realm-graphql-client';
import { ApolloClient } from 'apollo-client';
import gql from "graphql-tag";

async function login() {
  const credentials = Credentials.usernamePassword('username', 'password', true);
  const user = await User.authenticate(credentials, 'https://rustic-soft-chair.us1a.cloud.realm.io');
  console.log(user)

  const config = await GraphQLConfig.create( 
    user,
    `/default/__partial/${user.identity}`
  );
  console.log(config)

  const httpLink = concat(
    config.authLink,
    // Note: if using node.js, you'll need to provide fetch as well.
    new HttpLink({ uri: config.httpEndpoint })
  );
  console.log(httpLink)

  // Note: if using node.js, you'll need to provide webSocketImpl as well.
  const webSocketLink = new WebSocketLink({
    uri: config.webSocketEndpoint,
    options: {
      connectionParams: config.connectionParams,
    }
  });
  console.log(webSocketLink)

  const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  webSocketLink,
  httpLink,
  );

  // Finally, create the client
  const client = new ApolloClient({
    link: link,
    cache: new InMemoryCache()
  });
}
....```

<img width="1680" alt="screen shot 2018-10-26 at 9 48 16 am" src="https://user-images.githubusercontent.com/906931/47541767-bdab0b00-d904-11e8-9e91-ca3f1a1c9bec.png">

<img width="1680" alt="screen shot 2018-10-26 at 9 48 13 am" src="https://user-images.githubusercontent.com/906931/47541770-c3a0ec00-d904-11e8-893f-3646f03a73d4.png">

<img width="1680" alt="screen shot 2018-10-26 at 9 48 00 am" src="https://user-images.githubusercontent.com/906931/47541778-cac7fa00-d904-11e8-9b57-52d16de3bec3.png">

**Comment by nirinchev** [comment]
The stable GraphQL service/client don't support working with partial Realms. If you want to query/mutate a reference Realm, you need to open it directly with an admin user.

**Comment by henghonglee** [comment]
> If you want to query/mutate a reference Realm, you need to open it directly with an admin user

is there a reason for this restriction? seems like making my user into an admin user also doesnt allow it to create a partial realm (ie query/mutate a reference Realm)
it currently only works for the `realm-admin` user

**Comment by nirinchev** [comment]
It's just not implemented yet. We do plan to lift that restriction, the challenge is that it can cause significant load both on the sync server, and the GraphQL service node. The current recommendation is that you add a lightweight webserver that your web app will communicate with, then have it call into the GraphQL service using an admin user. This will allow you to prevent users from creating overly broad queries and you'll be able to massage the payload you send as response.

Alternatively, you can open a ticket at https://support.realm.io and ask for a prerelease version of the GraphQL service and client that supports working with query-based Realms.

**Comment by nirinchev** [comment]
This has been released as a technical preview - we may tweak the final API at a later point, but should be useable. The versions you need are [1.3.0 for the GraphQL Client](https://github.com/realm/realm-graphql/releases/tag/1.3.0) and [3.4.0 for the GraphQL Service](https://github.com/realm/realm-graphql-service/releases/tag/3.4.0).
