### ISSUE TITLE
Update readme, docs and any examples to use apollo-boost instead of apollo-client-preset

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-graphql#40]
[`apollo-client-preset`](https://npmjs.com/package/apollo-client-preset) is deprecated in favour of `apollo-boost`

> for the best quick start with Apollo Client, please use apollo-boost instead

**Comment by rolfdalhaug** [comment]
+1

**Comment by cbush** [comment]
https://github.com/realm/realm-graphql/commit/065e970ce67e0363ec7d73f0ea231094c86df11e
