### ISSUE TITLE
Invalid result when querying a null date

### ISSUE THREAD

**Issue by pierre-moire** [realm/realm-graphql#41]
I have an object with a null date and when I get the object through a GraphQL query the result appears to be not null : 

![image](https://user-images.githubusercontent.com/2143238/55155869-bb213b80-5158-11e9-85b8-8f4606dc4fba.png)

![image](https://user-images.githubusercontent.com/2143238/55155904-d2602900-5158-11e9-82fc-235c1be289d5.png)

The expected behavior would have been to get null in this field

**Comment by pierre-moire** [comment]
Additional notes : it is happening on Realm Cloud v3.19.0-cloud.2

**Comment by nirinchev** [comment]
Can you provide more details on how to repro this. I tried to do a trivial test and I get `null`-s:

<img width="821" alt="Screen Shot 2019-03-28 at 15 22 50" src="https://user-images.githubusercontent.com/2315687/55165406-a4391400-516d-11e9-9800-a95020eb99c6.png">
<img width="1031" alt="Screen Shot 2019-03-28 at 15 22 57" src="https://user-images.githubusercontent.com/2315687/55165408-a4391400-516d-11e9-8b10-3ec4010a6fa9.png">

**Comment by nirinchev** [comment]
Interestingly enough, this has been reported in the Cocoa repo as well: https://github.com/realm/realm-cocoa/issues/6112

**Comment by pierre-moire** [comment]
I have totally no idea on how to reproduce it except having a nullable date in the schema and a null data entry in the data...

**Comment by pierre-moire** [comment]
Additional note however : I also found the same bug on the ipad. I received a Date 1970 instead of a null date

**Comment by nirinchev** [comment]
So far, the clues we have is that this only happens when using query based sync.

**Comment by pierre-moire** [comment]
This is what we use, indeed

**Comment by nirinchev** [comment]
Cool, so it's very likely the same thing (the screenshots didn't expose that, so I only tested a full sync as that was quicker). We're working on a fix right now and hope to have something deployed soon.

**Comment by pierre-moire** [comment]
Thanks!

**Comment by ironage** [comment]
This was fixed in realm/realm-sync#2894 and released in sync 4.2.1 which is ROS version v3.20.0-rc.1. Deployed to cloud as raas v801, on April 5 2019.
