### ISSUE TITLE
Empty database after login

### ISSUE THREAD

**Issue by pierre-moire** [realm/realm-graphql#44]
I created a reference realm with classes and data inside.

When I log successfully, I subscribe to data I need to receive and the subscriptions are correctly saved in my partial realm.

However, data I required is never coming to my partial realm although there is no restriction in term of permissions (everyone group is still present and has access on everything)

In the reference database : 
![image](https://user-images.githubusercontent.com/2143238/55483296-96303b00-5626-11e9-920a-ca69eded3fee.png)

![image](https://user-images.githubusercontent.com/2143238/55483346-b102af80-5626-11e9-8ea0-47d88b104d11.png)

The Country _Class permission seem correct:

![image](https://user-images.githubusercontent.com/2143238/55483336-ac3dfb80-5626-11e9-8512-097324c1e87f.png)

![image](https://user-images.githubusercontent.com/2143238/55483372-b95aea80-5626-11e9-8dea-60801fb6fed7.png)

![image](https://user-images.githubusercontent.com/2143238/55483382-be1f9e80-5626-11e9-8ebf-3617efd65742.png)

![image](https://user-images.githubusercontent.com/2143238/55483390-c2e45280-5626-11e9-9a45-0963c749d0f2.png)

The user is correctly assigned to everyone group: 

![image](https://user-images.githubusercontent.com/2143238/55483437-dabbd680-5626-11e9-9030-a17f1ff5d63b.png)

and correctly set in _User

![image](https://user-images.githubusercontent.com/2143238/55483454-e4453e80-5626-11e9-8ede-d63b5202db12.png)

The partial exist for the user: 

![image](https://user-images.githubusercontent.com/2143238/55483479-f2935a80-5626-11e9-9c78-1e70c02dd1dc.png)

But nothing arrives inside: 

![image](https://user-images.githubusercontent.com/2143238/55483497-fcb55900-5626-11e9-8186-aa5abab7649a.png)

The subscriptions appear OK:

![image](https://user-images.githubusercontent.com/2143238/55483510-02ab3a00-5627-11e9-9671-b6e715973aac.png)

![image](https://user-images.githubusercontent.com/2143238/55483545-15257380-5627-11e9-806f-ea8a1f403609.png)

... but with "0 matches" in the Country column

Any idea why?

**Comment by pierre-moire** [comment]
Additionally, here are the privileges when I use the node js api instead to have info:
**Realm privileges** : 
  read: true,
  update: true,
  modifySchema: true,
  setPermissions: true

**Class privileges on Country** : 
  read: true,
  update: true,
  create: true,
  subscribe: true,
  setPermissions: true

**Privileges on __Class** : 
  read: true,
  update: true,
  create: true,
  subscribe: true,
  setPermissions: true

**Privileges on __Permission** :
  read: true,
  update: true,
  create: true,
  subscribe: false,
  setPermissions: false

**Privileges on __Role** :
  read: true,
  update: true,
  create: true,
  subscribe: true,
  setPermissions: true

**Comment by pierre-moire** [comment]
![image](https://user-images.githubusercontent.com/2143238/55488692-d2689900-5630-11e9-8790-3e64b663e213.png)

**Comment by ericjordanmossman** [comment]
@pierre-moire Would you be able to send the material through the channel I responded on?

**Comment by pierre-moire** [comment]
Yes sure, I just replied to your email

**Comment by pierre-moire** [comment]
Note: The bug seems to have "disappeared" after the realm object server update
