### ISSUE TITLE
Support TTL for subscriptions

### ISSUE THREAD

**Issue by Dids** [realm/realm-graphql#46]
As far as I can tell, the Realm GraphQL client doesn't have support for setting the time to live for subscriptions, and (as far as I know) Realm doesn't have a default TTL either.

I'm sure there are other recent features that are missing from the client, but I'm hoping this is still actively maintained, as I'm planning to make heavy use of this in a production web application (in conjunction with Realm Cloud and mobile applications using the native Realm clients).

**Comment by nirinchev** [comment]
The GraphQL client does not offer any API with regards to actually executing GraphQL queries - it handles authentication and urls. The query-based subscriptions are created via a regular mutation and you can specify the ttl there. The signature of the method is:

```
create*MyType*Subscription(query: String, sortBy: String, descending: Boolean, name: String, update: Boolean, timeToLive: Float)
```

I know that the docs for the GraphQL service are outdated and we'll improve them as we transition to a unified Mongo-Realm organization. For now, it's best to open a partial Realm via the GraphiQL explorer and use the autocompletion functionality to discover the API.

**Comment by Dids** [comment]
@nirinchev Thank you, that answers it perfectly then!

That said, should Realm Studio's built-in GraphiQL explorer work with createXSubscription (and delete/query subscription) methods? Because it neither auto-completes, nor accepts them as valid queries/mutations.

Closing this particular issue though, as everything is in order now.

**Comment by nirinchev** [comment]
Are you opening the partial Realm or the reference Realm with studio? These methods only exist on the partial one.

**Comment by Dids** [comment]
You're absolutely right, I was opening the reference Realm in GraphiQL, thanks again!
