### ISSUE TITLE
Queries hang indefinitely and error in Realm Cloud

### ISSUE THREAD

**Issue by Dids** [realm/realm-graphql#47]
I started facing an issue today, where the client can't seem to send any queries through, while this worked fine yesterday.

There were no changes to the project, and this happens across multiple users and environments (including CI). Also note that the partial Realm in question _does_ in fact exist, at least according to Realm Studio, but I can't open it, then again I haven't been able to open any partial Realm for a while (operation cancelled), so that's likely not related.

Error in Realm Cloud (repeats for every query attempt):
```
Unable to connect to a Realm (path: /<realm>/__partial/<userid>/graphql-client). Message: Bad WebSocket response 404 not found, category: realm::util::websocket::Error, code: 13, name: Error.
```

Not sure if this is a Realm Cloud issue or not, so opening an issue here as well.

**Comment by Dids** [comment]
**Update:**
- Deleting the partial Realm didn't fix it either, and still shows the same error on Realm Cloud
- Issue happens across all Realm Cloud instances, so may be related to the most recent update (v3.27.2)

**Comment by nirinchev** [comment]
I'm taking a look.

**Comment by s-turcheniuk** [comment]
same issue happens

**Comment by Eyesonly88** [comment]
Having this issue as well. Raised a support ticket about it too.

**Comment by Dids** [comment]
A fix was found and deployed. Should probably be fixed for everyone soon. :)

**Comment by nirinchev** [comment]
Yeah, if you are still experiencing issues, open a ticket with your instance name and we'll expedite a deployment.

**Comment by Eyesonly88** [comment]
@nirinchev still having issues! here's my support ticket https://support.realm.io/support/tickets/5251

**Comment by cheerly** [comment]
> Yeah, if you are still experiencing issues, open a ticket with your instance name and we'll expedite a deployment.

I think it has work,
