### ISSUE TITLE
Handling client resets

### ISSUE THREAD

**Issue by Dids** [realm/realm-graphql#49]
Does the Realm GraphQL client provide any way of handling Realm client resets?

I've tried everything I can think of, regarding clearing/stopping/destroying the Apollo client, but no matter what I do, Realm Cloud reports that "A client reset error has occurred", and the Realm GraphQL client is unable to parse any responses.

I've also tried `user.logOut()`, but with the same exact results.

I also use `InMemoryCache` with Apollo, which I assumed would've cleared the data automatically.

Lastly, I've tried resetting the Realm in question (partial/reference Realm) by removing it and recreating it, but this didn't help either.

**Comment by nirinchev** [comment]
The GraphQL service should handle those automatically. If it doesn't, we probably have a regression. If you can provide a simple repro case, that'll be super helpful.

**Comment by Dids** [comment]
I feel like it'll be harder to repro without an identical Realm Cloud instance/Realms/users. But, before I do that, I have more details and/or suggestions below, which I'd greatly appreciate your input on.

I caused this issue myself, by deleting all partial user Realms through Realm Studio, and this is when the errors started happening.
Even though I eventually deleted the primary Realm and all users (through Realm Studio), and recreated everything (same Realm name, same users), this still happened (both locally and in CI, and the CI shouldn't be caching anything other than node_modules).

All of this does make me think that it might be an issue in Realm Cloud, where it's holding on a reference to the old Realm, which would explain why deleting & recreating doesn't fix the issue, right?

**Comment by Dids** [comment]
Quick update on this: the only fix/workaround I've found so far, is to use a different name for the Realm. If I reuse the same name, the issue persists throughout every client, so it's not a local issue, but an issue on Realm Cloud (as far as I can tell).

**Comment by nirinchev** [comment]
Yes, it's the GraphQL service, not client that is responsible for handling that type of thing. If it isn't, that means something has regressed that hasn't been caught by testing. I did a trivial test and couldn't get it to happen, so might be a little more involved than what I tried.

**Comment by Dids** [comment]
Ah, that makes sense.

I'll try my best to create a minimal sample project, and update here if/when it's done, thanks!

**Comment by nirinchev** [comment]
I have managed to repro, don't worry about it. Seems to be caused by a change in the behavior of realm-js that broke certain assumptions in ROS. We're looking at it and hope to have a fix shortly. For now, the only workaround is the one you described.

**Comment by rouuuge** [comment]
got the same issue, but due to production realm im not able to change the name of the realm. has anyone a different workaround?

**Comment by nirinchev** [comment]
Open a ticket with the support team, they should be able to resolve it.

**Comment by rouuuge** [comment]
hi, I opened one 20 days ago, still no answer 👎 and if I get one I guess that's they only fix the issue on my realm cloud instance. But I'm interested to how i can force a client resets on myself.

**Comment by nirinchev** [comment]
This has been resolved. Support is working with @rouuuge to determine what their problem is.

**Comment by Dids** [comment]
@nirinchev @rouuuge This likely isn't going to be maintained anymore, I just wanted to let you know that this issue popped up again, and I've been trying to diagnose it with the MongoDB Support team (case 00801411), but there doesn't seem to be a solution, not yet at least.

Curious to know what the fix was and if it could still be applied to this now, either by myself to a fork, or to this repository, as we're still several months away from being able to migrate to MongoBD Realm.

Note that this is strictly about the legacy Realm Cloud, GraphQL and this particular library.
