### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by scolobey** [realm/realm-graphql#51]
When I first login, I store the token associated with the returned user object. 

When I later use this token With the following, I receive "invalid credentials".

```
const credentials = Credentials.jwt(token);
return User.authenticate(credentials, 'https://recipe-realm.us1.cloud.realm.io')
```

The token appears to decode correctly. It doesn't look to be expired. It just appears to be an invalid signature.

The links commented in the Credential class are 404
https://realm.io/docs/realm-object-server/latest#jwt-custom-authentication

I can just store the entire user object from my first authentication and pass that into 

```
GraphQLConfig.create(
      user,
      '/~/recipes'
    ); 
```

But then why have Credentials.jwt?

**Comment by nirinchev** [comment]
The docs for JWT auth have been moved here: https://docs.realm.io/sync/using-synced-realms/user-authentication/jwt-authentication

**Comment by scolobey** [comment]
Thanks @nirinchev 
Any idea why I would be able to access a Realm with the stored results of
`User.authenticate(credentials, 'https://my-realm.cloud.realm.io')`

But not with the token obtained from those results?
```
const credentials = Credentials.jwt(token);
User.authenticate(credentials, 'https://recipe-realm.us1.cloud.realm.io')
```

**Comment by nirinchev** [comment]
I'm confused - have you setup jwt auth? It seems like you're trying to use the refresh token as a token for jwt which is not the way it's intended to be used. Can you provide a minimal repro or a more complete code sample to help me understand what exactly you're trying to achieve?

**Comment by scolobey** [comment]
Sorry for the confusion.
I think you're right about using the refresh token improperly.
I did not understand that the token sent with the response from `User.authenticate`  was a refresh token. 

I am trying to signup and synch from a React frontend. 
I want to achieve these 3 goals.

  1. Create a Realm user.
  2. Create a Realm /~/recipes for that user to interact with.
  3. Query and mutate as needed.

This is my current understanding of how best to do this. But I'm not very confident this is the correct process.

  1. Call my server.
  2. Server calls Realm Object Server to create a user.
  4. Server calls Realm Object Server to create a Realm '/~/recipes'
  3. On success, server creates a valid JWT.
  4. JWT sent to web app.
  5. Web app runs queries and mutations against the realm through something like the following.

```
const credentials = Credentials.jwt(token);
const user = User.authenticate(credentials, 'https://recipe-realm.us1.cloud.realm.io')

GraphQLConfig.create(
      user,
      '/~/recipes'
); 

const client = config.createApolloClient();

    const response = await client.query({
      query: gql`
        query {
          recipes {
            title
          }
        }`
    });
```

So far, I've been able to both create and/or login a Realm user from the web app without a call to my backend by running something like the following from the client.
```
Credentials.usernamePassword()
User.authenticate(credentials, 'https://recipe-realm.us1.cloud.realm.io')
```
And I can then query a Realm if one already exists for the user, but I don't understand how to go about creating a new Realm for a new user.
