### ISSUE TITLE
Cannot fetch integers from Realm

### ISSUE THREAD

**Issue by bimusiek** [realm/realm-graphql#60]
We store timestamps in Realm as int. It is accessible through the Realm.Sync but when we try to fetch it through GraphQL, we get an error. 

## Error:
```
{
  "data": {
    "importerAuthenticationModels": null
  },
  "errors": [
    {
      "message": "Int cannot represent non 32-bit signed integer value: 1604585738795",
      "locations": [
        {
          "line": 11,
          "column": 7
        }
      ],
      "path": [
        "importerAuthenticationModels",
        0,
        "expiresAt"
      ]
    }
  ]
}
```

## QL query
```
  query ImporterAuthModels {
    importerAuthenticationModels {
      uniqueId
      id
      title
      subTitle
      imageUrl
      importerId
      additionalDataString
      rawStatus
      expiresAt
      doNotUseForSharing
    }
  }
``` 
## Our usecase
We are working on migrating from old Realm.Sync to new MongoDB Realm. 
Our way is to fetch all models through GraphQL on Node.js and push them to MongoDB via mongoose. 

This issue blocks us from migrating to new MongoDB Realm.
I know I can change the type of the field to string and then it would work, however it is already released to production so I would love to see solution from your side.

Possible solution for us:
- Let Realm GraphQL service return string instead of int for too big integers

If you have any other suggestions how we can fetch timestamps from GraphQL using current models, please tell me.

**Comment by hennasingh** [comment]
On Realm Studio, in the __configuration ( click show system realms to find this realm) realm, in ServiceConfig class,  edit the config for your graphQL Service and add {"presentIntsAsFloatsInSchema" : true}. The range of a float is ~2^53, which should be sufficient for the number above
