### ISSUE TITLE
Unable to install realm-graphql

### ISSUE THREAD

**Issue by dev-ios-sogo** [realm/realm-graphql#7]
hi folks, got this error just now when hoping to try out realm w/ graphql. 
```
npm install realm-graphql --save

**npm ERR! code E404
npm ERR! 404 Not Found: realm-graphql@latest**
```

Just to note, I have installed the ROS server side items needed for graphql support and had no issues. For example I can open up in a browser window the GraphiQL client

**Comment by nirinchev** [comment]
Sorry for that - there's an error in the readme. The correct package name is `realm-graphql-client` (https://www.npmjs.com/package/realm-graphql-client). Thanks for reporting it, I'll update the readme to avoid confusing others!

**Comment by dev-ios-sogo** [comment]
no worries! thanks for quick reply.
