### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by dev-ios-sogo** [realm/realm-graphql#8]
Whilst i know Realm & its api's well, I'm new to using GraphQL and it would be a great help, if you could provide us with a super simple hello world app - complete with all required node dependencies - so we can just download the repo, run "yarn" or npm install, and then run the app from cli. 

I've tried by using the attached simple apollo project (which works prior to adding any Realm GraphQL dependencies) but it's throwing this error:

![2018-01-12_15-42-34](https://user-images.githubusercontent.com/34407314/34880255-2f44edee-f7b0-11e7-9c06-7b0a9f9df65e.png)

![2018-01-12_15-43-26](https://user-images.githubusercontent.com/34407314/34880273-3fac97d6-f7b0-11e7-93ee-cb933e9a1466.png)

the project is attached here, feel free to run npm install, then point it to your own test ROS etc.. The edited code file is in /components/PostList.js

[Archive.zip](https://github.com/realm/realm-graphql/files/1626397/Archive.zip)

**Comment by dev-ios-sogo** [comment]
hey folks, just checking in on this one. even if in the interim you can just get me going with realm-graph-ql that would be great. I don't even mind sending a pull request with updates to your README here if I do get it working.

**Comment by bigfish24** [comment]
Can you verify that you have the GraphQL service installed with your Object Server as described here: https://docs.realm.io/platform/develop/integration/web-integration

**Comment by dev-ios-sogo** [comment]
I decided to start from scratch to ensure I didn't miss anything in the setup of ROS. It's a Digital Ocean instance, Ubuntu.

Installing ROS was perfect, great install experience :-)

```ros init sogo```
```cd sogo```

Then I tested starting ROS. All fine.

Stopped ROS. Then ran:

```npm install realm-graphql-service --save```

This threw an error, as follows:

```
ubuntu@realm-test-server:~/sogorealm/sogo$ npm install realm-graphql-service --save
npm WARN my-ros-app@1.0.0 No repository field.
npm WARN my-ros-app@1.0.0 No license field.

npm ERR! path /home/ubuntu/sogorealm/sogo/node_modules/realm-object-server/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/ubuntu/sogorealm/sogo/node_modules/realm-object-server/node_modules/abbrev' -> '/home/ubuntu/sogorealm/sogo/node_modules/realm-object-server/node_modules/.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-01-28T11_13_51_526Z-debug.log
```

**Comment by dev-ios-sogo** [comment]
hi folks, just checking in on this. very keen to get something up and working w/ Realm and GQL

**Comment by mgeerling** [comment]
@dev-ios-sogo , I think you've actually found a bug with `ros init`.  I was able to reproduce. 

remove the package-lock.json (`rm package-lock.json`)  Then proceed with the `npm install`.  

Will get this fixed ASAP

**Comment by dev-ios-sogo** [comment]
Thanks @mgeerling . I removed package-lock.json and it let me install ```realm-graphql-service``` on the server. I was also able to start up ROS afterwards without any errors. Next step for me on this is to now see if I can get GraphQL queries (from client) working against this ROS instance.

**Comment by mgeerling** [comment]
@dev-ios-sogo - Awesome!  I am going to close out this issue since it's a problem with `ros init` rather than graphQL.  If you run into other issues, feel free to post on forums.  I've also got a graphQL tutorial on the coming docs list.

**Comment by dev-ios-sogo** [comment]
Hey Matt, which forum should I post the GraphQL q’s to ?

 

I’ve hit a blocker on client side, where GraphQLConfig is throwing an error. Have I missed a param or have syntax incorrect ?

 

const user = await realmGQL.User.authenticate(

    credentials,

    'http://159.89.204.238:9080'

  );

 

  console.log('user is', user); ß- this is fine, I get an object

 

  const config = await realmGQL.GraphQLConfig.create({

    user: user,

    realmPath: `/testrealm`,

    authErrorHandler: error => {

      console.log('error', error);

    }

  });

 

***** the config call fails. Here is error:

 

(node:42912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Server for user must be specified

(node:42912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated

 

 

 

 

Regards,

Angus Johnston

Lead Developer

SOGO Golf

Mob: +61 400 44 29 23

**Comment by dev-ios-sogo** [comment]
Sorry folks – please ignore this email issues noted below. I started over with a clean slate, create-react-app à I got a React app w/ Apollo returning Realm data from a ROS. This was without any realm-graphql-client helpers.

 

However when I then try to import realm-graphql-client like so:

 

import { User, Credentials, GraphQLConfig } from 'realm-graphql-client';

 

it crashes the app.

 

Github ticket is here with full details: https://github.com/realm/realm-graphql/issues/10

 

 

 

Regards,

Angus Johnston

Lead Developer

SOGO Golf

Mob: +61 400 44 29 23

 

From: Angus Johnston <dev-ios@sogo.golf>
Date: Saturday, 3 February 2018 at 10:30 pm
To: realm/realm-graphql <reply@reply.github.com>, realm/realm-graphql <realm-graphql@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [realm/realm-graphql] hello world (#8)

 

Hey Matt, which forum should I post the GraphQL q’s to ?

 

I’ve hit a blocker on client side, where GraphQLConfig is throwing an error. Have I missed a param or have syntax incorrect ?

 

const user = await realmGQL.User.authenticate(

    credentials,

    'http://159.89.204.238:9080'

  );

 

  console.log('user is', user); ß- this is fine, I get an object

 

  const config = await realmGQL.GraphQLConfig.create({

    user: user,

    realmPath: `/testrealm`,

    authErrorHandler: error => {

      console.log('error', error);

    }

  });

 

***** the config call fails. Here is error:

 

(node:42912) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Server for user must be specified

(node:42912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated

 

 

 

 

Regards,

Angus Johnston

Lead Developer

SOGO Golf

Mob: +61 400 44 29 23
